name: Terraform CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7  # Specify your Terraform version

    # Cache Terraform provider plugins
    - name: Cache Terraform provider plugins
      uses: actions/cache@v2
      with:
        path: ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/*.tf') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    # Set AWS credentials as environment variables
    - name: Set AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV  # Replace with your desired region

    # Terraform initialization
    - name: Terraform Init
      run: terraform init

    # Terraform validate
    - name: Terraform Validate
      run: terraform validate

    # Terraform plan
    - name: Terraform Plan
      run: terraform plan

    # Terraform apply
    - name: Terraform Apply
      run: terraform apply -auto-approve

    # Optionally, you can add a destroy step
    - name: Terraform Destroy (Optional)
      run: terraform destroy -auto-approve
     if: github.ref == 'refs/heads/main'
